import MappingArray from "./Day/Day6__MappingArray/Components/MappingArray";
import ClassComponent from "./Day/Day7__ClassComponent/Components/ClassComponent";

export const folders = [
	{ day: "1", content: "JavaScript Refresher", component: <></> },
	{ day: "2", content: "Getting Started React", component: <></> },
	{ day: "3", content: "Setting Up", component: <></> },
	{ day: "4", content: "Components", component: <></> },
	{ day: "5", content: "Props", component: <></> },
	{ day: "6", content: "Mapping Array", component: <MappingArray /> },
	{ day: "7", content: "Class Component", component: <ClassComponent /> },
	{ day: "8", content: "States", component: <></> },
	{ day: "9", content: "Conditional Rendering", component: <></> },
	{ day: "10", content: "React Project Folder Structure", component: <></> },
	{ day: "11", content: "Events", component: <></> },
	{ day: "12", content: "Forms", component: <></> },
	{ day: "13", content: "Uncontrolled Component", component: <></> },
	{ day: "14", content: "Component Life Cycles", component: <></> },
	{ day: "15", content: "Third Party Packages", component: <></> },
	{ day: "16", content: "Higher Order Component", component: <></> },
	{ day: "17", content: "React Router", component: <></> },
	{ day: "18", content: "Fetch and Axios", component: <></> },
	{ day: "19", content: "Projects", component: <></> },
	{ day: "20", content: "Projects", component: <></> },
	{ day: "21", content: "Introducing React Hooks", component: <></> },
	{ day: "22", content: "Form Using React Hooks", component: <></> },
	{ day: "23", content: "Fetching Data Using Hooks", component: <></> },
	{ day: "24", content: "Projects", component: <></> },
	{ day: "25", content: "Custom Hooks", component: <></> },
	{ day: "26", content: "Context", component: <></> },
	{ day: "27", content: "useRef", component: <></> },
	{ day: "28", content: "Project", component: <></> },
	{ day: "29", content: "Explore", component: <></> },
	{ day: "30", content: "Conclusion", component: <></> },
];
