export const folders = [
	{ day: "1", content: "JavaScript Refresher" },
	{ day: "2", content: "Getting Started React" },
	{ day: "3", content: "Setting Up" },
	{ day: "4", content: "Components" },
	{ day: "5", content: "Props" },
	{ day: "6", content: "Mapping Array" },
	{ day: "7", content: "Class Component" },
	{ day: "8", content: "States" },
	{ day: "9", content: "Conditional Rendering" },
	{ day: "10", content: "React Project Folder Structure" },
	{ day: "11", content: "Events" },
	{ day: "12", content: "Forms" },
	{ day: "13", content: "Uncontrolled Component" },
	{ day: "14", content: "Component Life Cycles" },
	{ day: "15", content: "Third Party Packages" },
	{ day: "16", content: "Higher Order Component" },
	{ day: "17", content: "React Router" },
	{ day: "18", content: "Fetch and Axios" },
	{ day: "19", content: "Projects" },
	{ day: "20", content: "Projects" },
	{ day: "21", content: "Introducing React Hooks" },
	{ day: "22", content: "Form Using React Hooks" },
	{ day: "23", content: "Fetching Data Using Hooks" },
	{ day: "24", content: "Projects" },
	{ day: "25", content: "Custom Hooks" },
	{ day: "26", content: "Context" },
	{ day: "27", content: "useRef" },
	{ day: "28", content: "Project" },
	{ day: "29", content: "Explore" },
	{ day: "30", content: "Conclusion" },
];
